### ISSUE TITLE
rubypants translates --> into &#8211;>

### ISSUE THREAD

**Issue by ibc** [jmcnevin/rubypants#1]
Hi, when I enable rubypants filter in a HTML page, this filter produces an error as it translates "-->" (end of commented code) into "& # 8 2 1 1 ; >"  (I use space because if not github/markdown converts it into "-->".

Some browsers (Konqueror, Chrome) accept such syntax but Firefox doesn't understand that as "end of comment" and the page is wrongly rendered.

**Comment by agriffis** [comment]
@snan Any chance you'd make a PR for this? I'm curious about your fix but your site's cert is expired and it would be nice to see the changes in github's interface anyway. Otherwise, perhaps you could just cut-n-paste the diff here. Thanks!

**Comment by snan** [comment]
diff --git a/lib/rubypants/core.rb b/lib/rubypants/core.rb
    index 03a210f..7f7e3a2 100644
    --- a/lib/rubypants/core.rb
    +++ b/lib/rubypants/core.rb
    @@ -336,7 +336,7 @@ class RubyPants < String
       # Chad Miller in the Python port of SmartyPants.
       #
       def tokenize
    -    tag_soup = /([^<]*)(<[^>]*>)/
    +    tag_soup = /([^<]*)()/

	 tokens = []

**Comment by jmcnevin** [comment]
Sorry for keeping this PR in limbo for so long.  Would either of you be interested in taking over maintenance of this gem?

https://github.com/jmcnevin/rubypants/issues/6

**Comment by agriffis** [comment]
Here is what I used:

```ruby
tag_soup = /([^<]*)(<!--.*?-->|<[^>]*>)/
```

This treats the entire comment as an HTML tag, so that it can avoid making typographic replacements inside the comment, and also so that it doesn't treat `-->` as special unless it's part of a comment.
