### ISSUE TITLE
run on travis

### ISSUE THREAD

**Issue by agriffis** [jmcnevin/rubypants#10]
We're registered with travis and codecov, see #9, however we need `.travis.yml` and whatever else to actually run our tests and collect coverage data. Then of course badges in the README

**Comment by cromwellryan** [comment]
@agriffis any specific ruby versions you're interested in testing? #11 get's things building successfully (tests run).

**Comment by agriffis** [comment]
@cromwellryan thanks! Since https://github.com/jekyll/jekyll is a downstream consumer of rubypants via https://github.com/scampersand/jekyll-pants maybe we could test on the same versions. In fact I think that's what I did in https://github.com/scampersand/jekyll-pants/blob/master/.travis.yml
