### ISSUE TITLE
Add support for french quotes (&laquo; and &raquo;)

### ISSUE THREAD

**Issue by iamweird** [jmcnevin/rubypants#2]
Hi, I'm using RubyPants with Jekyll + Redcarpet on my website. My website is in Russian and by the Russian typography rules, &laquo;French quotes&raquo; (*&amp;laquo;* and *&amp;raquo;*) are required instead of straight quotes(' and ") or curly quotes - &lsquo;single&rsquo; (*&amp;lsquo;* and *&amp;rsquo;*) or &ldquo;double&rdquo; (*&amp;ldquo;* and *&amp;rdquo;*).

Is there any chance to get a setting to switch quote type? Or maybe I'm missing existing one.

Thanks!

**Comment by agriffis** [comment]
@iamweird You should be able to do this by calling with a modified entities hash. For example:

```ruby
entities = {
  :double_left_quote => '&laquo;',
  :double_right_quote => '&raquo;'
}
RubyPants.new(str, [2], entities).to_html
```
