### ISSUE TITLE
Need new maintainer

### ISSUE THREAD

**Issue by jmcnevin** [jmcnevin/rubypants#6]
Hey all.  I adopted this gem under the assumption that I would actually have time to maintain it.  Unfortunately, I'm no longer working on any projects that use it, and meatspace issues have ensured I really don't have any free time to make improvements.  

Would anyone else be interested in taking over maintenance of this gem?

**Comment by agriffis** [comment]
@jmcnevin If you'd like to add me as a maintainer alongside yourself (rather than handing it off entirely) then I could help with the outstanding PR and issues. I have a jekyll plugin that depends on this gem. https://github.com/scampersand/jekyll-pants

**Comment by agriffis** [comment]
Thanks @jmcnevin! Do you want to give me gem push perms too, or would you rather do that yourself? http://guides.rubygems.org/publishing/#push-permissions-on-rubygemsorg

**Comment by agriffis** [comment]
Should have mentioned, I'm agriffis on rubygems too. https://rubygems.org/profiles/agriffis

**Comment by jmcnevin** [comment]
You're all set!
