### ISSUE TITLE
Precede dashes by a non-breaking space (or thinspace)

### ISSUE THREAD

**Issue by vermiculus** [jmcnevin/rubypants#7]
Lines in a paragraph should never start with a dash – use a non-breaking space or a thinspace to remove that possibility.

Likely fix at https://github.com/jmcnevin/rubypants/blob/b2736f5d62df5c69dc9e77477ed4d9b472107227/lib/rubypants/core.rb#L329

**Comment by agriffis** [comment]
Could you elaborate on the problem? Also that link points into the `stupefy_entities` function, is that what you intended?

**Comment by vermiculus** [comment]
Ah, nope – sorry: [correct link](https://github.com/jmcnevin/rubypants/blob/b2736f5d62df5c69dc9e77477ed4d9b472107227/lib/rubypants/core.rb#L375)

Here's a 'bad' paragraph:

> This is just some filler text. It doesn't say much, but it doesn't need to: its sole purpose is to get – to begin a new line.

And here's a 'good' paragraph:

> This is just some filler text. It doesn't say much, but it doesn't need to: its sole purpose is to get – to begin a new line – a plan thwarted by `&#160;`.

It's just a rule of typography; [here's a reference](http://www.sussex.ac.uk/informatics/punctuation/hyphenanddash/dash).

**Comment by agriffis** [comment]
@vermiculus That link seems to go to "def default_entities" ... is that what you intended? I'm not seeing the connection between that and "likely fix"

Regarding "bad" paragraph and "good" paragraph, here's what shows in my browser. I think this is also not what you intended:

![screenshot from 2016-08-22 19-52-23](https://cloud.githubusercontent.com/assets/50637/17875683/0aef92bc-68a2-11e6-98c1-3ebdf7c5f6e0.png)

I think this is the paragraph you meant from the reference. Pasting here for safekeeping:

> When a dash falls between the end of one line and the beginning of the next, you should try to ensure that the dash is placed at the end of the first line and not at the beginning of the second, if you can.

Do you want to provide a PR?

**Comment by vermiculus** [comment]
Hm, this is what shows on my browser:
<img width="696" alt="screen shot 2016-08-22 at 10 28 30 pm" src="https://cloud.githubusercontent.com/assets/2082195/17879474/d9e2eda2-68b7-11e6-9145-286fbbe2535e.png">

Anyway, I'll work on providing a PR.

**Comment by vermiculus** [comment]
The idea is to replace every recognized ASCII endash with a thinspace+endash – would that not be in `default_entities`? (I'll freely admit I don't know Ruby beyond `hello, world`.)

**Comment by agriffis** [comment]
Unfortunately in my own testing it appears that Chrome and Firefox both will also split lines between word and dash, for example "hi—just saying—this is an example" might be rendered with "—just" or "—this" starting a line. However both browsers seem to change their behavior if the character prior to the dash is a non-breaking space, either &nbsp; or [&#65279; (zero-width non-breaking space)](http://www.fileformat.info/info/unicode/char/feff/index.htm)

So the fuller fix, ignoring the various modes, should be something like:

1. "foo -- bar" becomes "foo&nbsp&#8212; bar"
2. "foo--bar" becomes "foo&#65279;&#8212;bar"

This goes beyond modifying `default_entities` and should likely be configurable in options.

**Comment by agriffis** [comment]
@vermiculus released v0.5.1 which should fix this for you. Let me know!
