### ISSUE TITLE
add travis testing and coverage

### ISSUE THREAD

**Issue by agriffis** [jmcnevin/rubypants#9]
@jmcnevin would you mind registering this project at https://travis-ci.org/ and https://codecov.io/

I'll get it all running but I can't do the registration since it's your project.

**Comment by jmcnevin** [comment]
All set: 
https://travis-ci.org/jmcnevin/rubypants
https://codecov.io/gh/jmcnevin/rubypants

**Comment by agriffis** [comment]
Thanks!
